ByMe.Presentation/Areas/Sales/Controllers/SalesOrderController.cs
using BuyMe.Application.Branch.Queries;
using BuyMe.Application.Common.Exceptions;
using BuyMe.Application.Common.Models;
using BuyMe.Application.Customer.Queries.GetCustomers;
using BuyMe.Application.SalesOrder.Commonds;
using BuyMe.Application.SalesOrder.Commonds.DeleteSalesOrder;
using BuyMe.Application.SalesOrder.Queries;
using BuyMe.Application.SalesType.Queries;
using ByMe.Presentation.Helper.PdfDocuments;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.EJ2.Base;


namespace ByMe.Presentation.Areas.Sales.Controllers
{
    [Authorize(Roles = ApplicationRoles.SalesOrder)]
    public class SalesOrderController : BaseController
    {
        private readonly ISalesOrderDocument salesOrderDocument;

        public SalesOrderController(ISalesOrderDocument salesOrderDocument)
        {
            this.salesOrderDocument = salesOrderDocument;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UrlDatasource([FromBody] DataManagerRequest dm)
        {
            var result = await Mediator.Send(new GetSalesOrdersQuery() { DM = new DataManager(dm.Take, dm.Skip, dm.Search?.FirstOrDefault()?.Key) });
            return Json(result);
        }

        public async Task<ActionResult> CreateEdit([FromBody] CRUDModel<CreateEditSOCommond> value)
        {
            _ = value ?? throw new BadRequestException("Invalid Data");
            value.Value.SalesOrderId = await Mediator.Send(value.Value);
            return Json(value.Value);
        }

        public async Task<IActionResult> Print(long salesOrderId)
        {

            return File(await salesOrderDocument.GetSalesOrderPDfAsync(salesOrderId), "application/pdf");


        }

        public async Task<ActionResult> Details(long salesOrderId)
        {
            var so = await Mediator.Send(new GetSalesOrderQuery(salesOrderId));
            return View(so);
        }

        public async Task<ActionResult> GetById(long id)
        {
            var so = await Mediator.Send(new GetSalesOrderQuery(id));
            return Json(so);
        }

        public async Task<ActionResult> Delete([FromBody] CRUDModel<SalesOrderDto> value)
        {
            _ = await Mediator.Send(new DeleteSalesOrderCommond() { SalesOrderId = long.Parse(value.Key.ToString()) });
            return Json(value);
        }

        public async Task<IActionResult> EditAddPartial([FromBody] CRUDModel<CreateEditSOCommond> value)
        {
            ViewBag.Customers = (await Mediator.Send(new GetCustomersQurery())).result;
            ViewBag.Branches = (await Mediator.Send(new GetBranchesQuery())).result;
            ViewBag.SalesTypes = (await Mediator.Send(new GetSalesTypeQuery())).result;
            return PartialView("_CreateEditPartial", value.Value);
        }
    }
}

ByMe.Presentation/Areas/Sales/Views/SalesOrder/Details.cshtml
@model BuyMe.Application.SalesOrder.Queries.SalesOrderDto

@using Newtonsoft.Json;
<link rel="stylesheet" href="~/css/grid.css" />
<!-- Content Header (Page header) -->

<!-- Main content -->
<section class="content box">

    <div class="control-section">
        <div class="box-header">
            <h3 class="box-title">Order Details</h3>
        </div>
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        Order Number
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="SalesOrderName" readonly />
                    </dd>
                    <dt>
                        Branch
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="BranchName" readonly />
                    </dd>
                    <dt>
                        Customer
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="CustomerName" readonly />
                    </dd>
                </dl>
            </div>
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        OrderDate
                    </dt>
                    <dd>
                        <input class="form-control" value="@(Model.OrderDate.ToShortDateString())" readonly />
                    </dd>
                    <dt>
                        DeliveryDate
                    </dt>
                    <dd>

                        <input class="form-control" value="@(Model.DeliveryDate?.ToShortDateString())" readonly />
                    </dd>
                    <dt>
                        Currency
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="CurrencyCode" readonly />
                    </dd>
                    <dt>
                        Sales Type
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="SalesTypeName" readonly />
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</section>
<!-- Main content -->
<section class="content">
    <div class="control-section">
        <ejs-grid id="Grid" actionFailure="actionFailure"  actionComplete="actionComplete" toolbar="@(new List<string>() { "Add", "Edit", "Delete" })" allowPaging="true">
            <e-data-manager url="/Sales/SalesOrderLine/UrlDataSource?salesOrderId=@Model.SalesOrderId" insertUrl="/Sales/SalesOrderLine/CreateEdit" updateUrl="/Sales/SalesOrderLine/CreateEdit" removeUrl="/Sales/SalesOrderLine/Delete" adaptor="UrlAdaptor"></e-data-manager>
            <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true" mode="Dialog" template='#dialogtemplate'></e-grid-editSettings>
            <e-grid-columns>
                <e-grid-column field="ProductName" headerText="Product" type="string"></e-grid-column>
                <e-grid-column field="Description" allowSearching="false" headerText="Description" type="string"></e-grid-column>
                <e-grid-column field="Quantity"  headerText="Qty" type="string"></e-grid-column>
                <e-grid-column field="Price" headerText="Price"  ></e-grid-column>
                <e-grid-column field="Amount" headerText="Amount"></e-grid-column>
                <e-grid-column field="DiscountPercentage" headerText="Disc%"></e-grid-column>
                <e-grid-column field="SubTotal" headerText="SubTotal"></e-grid-column>
                <e-grid-column field="TaxPercentage" headerText="Tax%"></e-grid-column>
                <e-grid-column field="Total" headerText="Total"></e-grid-column>
                <e-grid-column field="SalesOrderId" defaultValue="@Model.SalesOrderId" visible="false"></e-grid-column>
                <e-grid-column field="ProductId" visible="false"></e-grid-column>
                <e-grid-column field="DiscountAmount" visible="false"></e-grid-column>
                <e-grid-column field="TaxAmount" visible="false"></e-grid-column>
                <e-grid-column field="SalesOrderLineId" headerText="" allowSearching="false" allowFiltering="false" isPrimaryKey="true" visible="false"></e-grid-column>
            </e-grid-columns>
        </ejs-grid>
    </div>
</section><!-- /.content -->
<section class="content box box-primary">
    <div class="control-section">
        <div class="row">
            <div class="col-md-8">
                <dl class="dl-horizontal">
                    <dt>
                       Remarks
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="Remarks" readonly />
                    </dd>
                </dl>
            </div>
            <div class="col-md-4">
                <dl class="dl-horizontal">
                    <dt>
                        Amount
                    </dt>
                    <dd>
                       <input class="form-control" asp-for="Amount" readonly />
                    </dd>
                    <dt>
                        Discount
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="Discount" readonly />
                    </dd>
                    <dt>
                        SubTotal
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="SubTotal" readonly />
                    </dd>
                    <dt>
                        Tax
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="Tax" readonly />
                    </dd>
                    <dt>
                        Freight
                    </dt>
                    <dd>
                        <input class="form-control" asp-for="Freight" readonly />
                    </dd>
                </dl>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <a class="btn btn-primary" href="/Sales/SalesOrder">Back</a>
                <a class="btn btn-warning" target="_blank" href="/Sales/SalesOrder/Print?salesOrderId=@Model.SalesOrderId" style="float:right">Print</a>
            </div>
        </div>
    </div>
</section>
<script id='dialogtemplate' type="text/x-template">
    <div id="dialogTemp"></div>
</script>

<script src="~/js/grid.js"></script>
<script>

        function actionFailure(args) {
          displayErrors(args)
        }
        function actionComplete(args) {
           if (args.requestType === 'beginEdit' || args.requestType === 'add') {
            args.form.ej2_instances[0].addRules('ProductId', { required: true });
                let spinner = ej.popups.createSpinner({ target: args.dialog.element });
                ej.popups.showSpinner(args.dialog.element);
                if (args.requestType === 'beginEdit' || args.requestType === 'add') {
                    var ajax = new ej.base.Ajax({
                        url: "@Url.Action($"EditAddPartial", "SalesOrderLine")", //render the partial view
                        type: "POST",
                        contentType: "application/json",
                        data: JSON.stringify({ value: args.rowData })
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form);
                        ej.popups.hideSpinner(args.dialog.element);
                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }

            }
            if (args.requestType == 'save' || args.requestType == 'delete') {
                RewriteTotal();
            }
        }
        function RewriteTotal() {
            $.ajax({
                type: 'GET',
                url: `/Sales/SalesOrder/GetById/${@(Model.SalesOrderId)}`,
                success: function (data) {
                    $('#Amount').val(data.Amount);
                    $('#SubTotal').val(data.SubTotal);
                    $('#Discount').val(data.Discount);
                    $('#Tax').val(data.Tax);
                    $('#Freight').val(data.Freight);
                    $('#Total').val(data.Total);
                }
            });
        }
</script>
<script type="text/javascript">
    function productChange(e) {
        debugger;
        if (e.value != 0) {
            $.ajax({
                url: `/Inventory/Product/GetProductPrice?productId=${e.value}`,
                type: 'GET',
                success: function (data) {
                    $("#Price").val(data.DefaultSellingPrice);
                }
            })
        }

    }
</script>

ByMe.Presentation/Areas/Sales/Views/SalesOrder/Index.cshtml
@using Newtonsoft.Json;
<link rel="stylesheet" href="~/css/grid.css" />
<style>
    .e-MT_List:before {
        content: '\e605';
        color: #3c8dbc;
    }

    .e-icons {
        font-size: 20px;
    }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        SalesOrder
        <small>Sales</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>SalesOrder</a></li>
        <li class="active">Sales</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="control-section">
        <ejs-grid id="Grid" load="load" actionFailure="actionFailure" actionComplete="actionComplete" toolbar="@(new List<string>() { "Add", "Edit", "Delete","Print","Search" })" allowPaging="true">
            <e-data-manager url="/Sales/SalesOrder/UrlDataSource" insertUrl="/Sales/SalesOrder/CreateEdit" updateUrl="/Sales/SalesOrder/CreateEdit" removeUrl="/Sales/SalesOrder/Delete" adaptor="UrlAdaptor"></e-data-manager>
            <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true" mode="Dialog" template='#dialogtemplate'></e-grid-editSettings>
            <e-grid-columns>

                <e-grid-column field="SalesOrderName" headerText="SalesOrder Name" type="string"></e-grid-column>
                <e-grid-column field="BranchName" allowSearching="false" headerText="Branch" type="string"></e-grid-column>
                <e-grid-column field="CustomerName" headerText="Customer" type="string"></e-grid-column>
                <e-grid-column field="OrderDate" type="date" headerText="OrderDate"></e-grid-column>
                <e-grid-column field="DeliveryDate" type="date" headerText="DeliveryDate"></e-grid-column>
                <e-grid-column field="CompanyId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="CustomerId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="CurrencyId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="BranchId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="SalesTypeId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="Freight" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="Remarks" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="SalesOrderId" headerText="" allowSearching="false" allowFiltering="false" isPrimaryKey="true" template="#salesOrderTemp"></e-grid-column>
            </e-grid-columns>
        </ejs-grid>
    </div>
</section><!-- /.content -->
<script id="salesOrderTemp" type="text/x-template">
    <a rel='nofollow'  href="/Sales/SalesOrder/Details?salesOrderId=${SalesOrderId}"><span class="e-icons e-MT_List"></span></a>
</script>
<script id='dialogtemplate' type="text/x-template">
    <div id="dialogTemp"></div>
</script>
<script src="~/js/grid.js"></script>
<script>
        function load(args) {
            this.columns[3].format = { type: 'date', format: 'dd/MM/yyyy' };
            this.columns[4].format = { type: 'date', format: 'dd/MM/yyyy' };
        }
        function actionFailure(args) {
          displayErrors(args)
        }
    function actionComplete(args) {
        if (args.requestType === 'beginEdit' || args.requestType === 'add') {
            args.form.ej2_instances[0].addRules('BranchId', { required: true });
                let spinner = ej.popups.createSpinner({ target: args.dialog.element });
                ej.popups.showSpinner(args.dialog.element);
                if (args.requestType === 'beginEdit' || args.requestType === 'add') {
                    var ajax = new ej.base.Ajax({
                        url: "@Url.Action($"EditAddPartial", "SalesOrder")", //render the partial view
                        type: "POST",
                        contentType: "application/json",
                        data: JSON.stringify({ value: args.rowData })
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); //Render the edit form with selected record
                        args.form.elements.namedItem('CustomerId').focus();
                        ej.popups.hideSpinner(args.dialog.element);
                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }
            }
        }
</script>
<script type="text/javascript">
        function branchChange(e) {
            if (e.value!=0) {
                $.ajax({
                    url: `/Config/Currency/GetBranchCurrency?branchId=${e.value}`,
                    type: 'GET',
                    success: function (data) {
                        $("#CurrencyCode").val(data.CurrencyCode);
                        $("#CurrencyId").val(data.CurrencyId);

                    }
                })
            }

    }
</script>

ByMe.Presentation/Areas/Sales/Views/SalesOrder/Print.cshtml
@using BuyMe.Application.SalesOrder.Queries
@using BuyMe.Application.SalesOrderLine.Queries
@{
    Layout = "_Print";
    ViewBag.Title = "Print Order";
}

@model (SalesOrderDto order, IList<SalesOrderLineDto> salesOrderLines)

    <div class="row">
        <div class="col-md-6" style="display:inline-block">
            <dl class="dl-horizontal">
                <dt>
                    Order Number
                </dt>
                <dd>
                    @Model.order.SalesOrderName
                </dd>
                <dt>
                    Branch
                </dt>
                <dd>
                    @Model.order.BranchName
                </dd>
                <dt>
                    Customer
                </dt>
                <dd>
                    @Model.order.CustomerName
                </dd>
            </dl>
        </div>
        <div class="col-md-6" style="display:inline-block;float:right">
            <dl class="dl-horizontal">
                <dt>
                    OrderDate
                </dt>
                <dd>
                    @(Model.order.OrderDate.ToShortDateString())
                </dd>
                <dt>
                    DeliveryDate
                </dt>
                <dd>
                    @(Model.order.DeliveryDate?.ToShortDateString())
                </dd>
                <dt>
                    Currency
                </dt>
                <dd>
                    @Model.order.CurrencyCode
                </dd>
                <dt>
                    Sales Type
                </dt>
                <dd>
                    @Model.order.SalesTypeName
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Qty</th>
                    <th>Price</th>
                    <th>Amt</th>
                    <th>Disc</th>
                    <th>SubTotal</th>
                    <th>Tax</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model.salesOrderLines)
                {
                    <tr>
                        <td>
                            @item.ProductName
                        </td>
                        <td>
                            @item.Quantity
                        </td>
                        <td>
                            @item.Price
                        </td>
                        <td>
                            @item.Amount
                        </td>
                        <td>
                            @item.DiscountAmount
                        </td>
                        <td>
                            @item.SubTotal
                        </td>
                        <td>
                            @item.TaxAmount
                        </td>
                        <td>
                            @item.Total
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="col-md-8" style="display:inline-block;float:right">
            <dl>
                <dt>
                    Remarks
                </dt>
                <dd>
                    @Model.order.Remarks
                </dd>
            </dl>
        </div>
        <div class="col-md-4" style="display:inline-block">
            <dl>
                <dt>
                    Amount
                </dt>
                <dd>
                    @Model.order.Amount
                </dd>
                <dt>
                    Discount
                </dt>
                <dd>
                    @Model.order.Discount
                </dd>
                <dt>
                    SubTotal
                </dt>
                <dd>
                    @Model.order.SubTotal
                </dd>
                <dt>
                    Tax
                </dt>
                <dd>
                    @Model.order.Tax
                </dd>
                <dt>
                    Freight
                </dt>
                <dd>
                    @Model.order.Freight
                </dd>
            </dl>
        </div>
    </div>

ByMe.Presentation/Areas/Sales/Views/SalesOrder/_CreateEditPartial.cshtml
@using BuyMe.Application.SalesOrder.Commonds
@using Newtonsoft.Json
@model CreateEditSOCommond
@{
    Layout = null;
}
<style>
    .dropDownListTop {
        margin-top: 15px;
    }
</style>
<div>
    <input asp-for="SalesOrderId" type="hidden" />
    <input asp-for="CurrencyId" type="hidden" />
    <input asp-for="CompanyId" type="hidden" />
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="SalesOrderName" readonly />
                <span class="e-float-line"></span>
                <label asp-for="SalesOrderName" class="e-float-text e-label-top">SalesOrder #</label>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="dropDownListTop">
                <ejs-dropdownlist ejs-for="CustomerId" placeholder="Select Customer" dataSource="@ViewBag.Customers" popupHeight="200px">
                    <e-dropdownlist-fields text="CustomerName" value="Id"></e-dropdownlist-fields>
                </ejs-dropdownlist>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="OrderDate" type="date" />
                <span class="e-float-line"></span>
                <label asp-for="OrderDate" class="e-float-text e-label-top">OrderDate</label>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="DeliveryDate" type="date" />
                <span class="e-float-line"></span>
                <label asp-for="DeliveryDate" class="e-float-text e-label-top">DeliveryDate</label>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="Remarks" />
                <span class="e-float-line"></span>
                <label asp-for="Remarks" class="e-float-text e-label-top">Remarks</label>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="dropDownListTop">
                <ejs-dropdownlist ejs-for="SalesTypeId" placeholder="SalesType" dataSource="@ViewBag.SalesTypes" popupHeight="200px">
                    <e-dropdownlist-fields text="SalesTypeName" value="Id"></e-dropdownlist-fields>
                </ejs-dropdownlist>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="dropDownListTop">
                <ejs-dropdownlist ejs-for="BranchId" change="branchChange" dataSource="@ViewBag.Branches" placeholder="Select Branch" popupHeight="200px">
                    <e-dropdownlist-fields text="BranchName" value="BranchId"></e-dropdownlist-fields>
                </ejs-dropdownlist>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <input readonly asp-for="CurrencyCode" />
                <span class="e-float-line"></span>
                <label class="e-float-text e-label-top">Currency</label>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="Freight" />
                <span class="e-float-line"></span>
                <label class="e-float-text e-label-top">Freight</label>
            </div>
        </div>
    </div>
</div>

<ejs-scripts></ejs-scripts>