ByMe.Presentation/Areas/Sales/Controllers/ShipmentController.cs
using BuyMe.Application.Branch.Queries;
using BuyMe.Application.Common.Exceptions;
using BuyMe.Application.Customer.Queries.GetCustomers;
using BuyMe.Application.SalesOrder.Commonds.DeleteSalesOrder;
using BuyMe.Application.SalesOrder.Commonds;
using BuyMe.Application.SalesOrder.Queries;
using BuyMe.Application.SalesOrderLine.Queries;
using BuyMe.Application.SalesType.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.EJ2.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BuyMe.Application.Common.Models;
using Microsoft.AspNetCore.Authorization;
using BuyMe.Application.Shipment.Queries;
using BuyMe.Application.Shipment.Commonds;
using BuyMe.Application.WarehouseINV.Queries;
using BuyMe.Application.ShipmentType.Queries;

namespace ByMe.Presentation.Areas.Sales.Controllers
{
    [Authorize(Roles = ApplicationRoles.Shipment)]
    public class ShipmentController:BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UrlDatasource([FromBody] DataManagerRequest dm)
        {
            var result = await Mediator.Send(new GetShipmentsQuery() { DM = new DataManager(dm.Take, dm.Skip, dm.Search?.FirstOrDefault()?.Key) });
            return Json(result);
        }

        public async Task<ActionResult> CreateEdit([FromBody] CRUDModel<CreateEditShipCommond> value)
        {
            _ = value ?? throw new BadRequestException("Invalid Data");
            value.Value.ShipmentId = await Mediator.Send(value.Value);
            return Json(value.Value);
        }

        public async Task<ActionResult> GetById(long id)
        {
            var so = await Mediator.Send(new GetSalesOrderQuery(id));
            return Json(so);
        }

        public async Task<ActionResult> Delete([FromBody] CRUDModel<ShipmentDto> value)
        {
            _ = await Mediator.Send(new DeleteShipCommond() { ShipmentId = long.Parse(value.Key.ToString()) });
            return Json(value);
        }

        public async Task<IActionResult> EditAddPartial([FromBody] CRUDModel<CreateEditShipCommond> value)
        {
            ViewBag.Warhouses = (await Mediator.Send(new GetWarehousesQuery())).result;
            ViewBag.SalesOrders = (await Mediator.Send(new GetSalesOrdersQuery())).result;
            ViewBag.ShipmentTypes = (await Mediator.Send(new GetShipmentTypeQuery())).result;
            return PartialView("_CreateEditPartial", value.Value);
        }
    }
}

ByMe.Presentation/Areas/Sales/Views/Shipment/Index.cshtml
@using Newtonsoft.Json;
<link rel="stylesheet" href="~/css/grid.css" />
<style>
    .e-MT_List:before {
        content: '\e605';
        color: #3c8dbc;
    }

    .e-icons {
        font-size: 20px;
    }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Shipment
        <small>Sales</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Shipment</a></li>
        <li class="active">Sales</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="control-section">
        <ejs-grid id="Grid" load="load" actionFailure="actionFailure" actionComplete="actionComplete" toolbar="@(new List<string>() { "Add", "Edit", "Delete","Print","Search" })" allowPaging="true">
            <e-data-manager url="/Sales/Shipment/UrlDataSource" insertUrl="/Sales/Shipment/CreateEdit" updateUrl="/Sales/Shipment/CreateEdit" removeUrl="/Sales/Shipment/Delete" adaptor="UrlAdaptor"></e-data-manager>
            <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true" mode="Dialog" template='#dialogtemplate'></e-grid-editSettings>
            <e-grid-columns>
                <e-grid-column field="ShipmentName" headerText="Shipment Name" type="string"></e-grid-column>
                <e-grid-column field="IsFullShipment" allowSearching="false" headerText="FullShipment" displayAsCheckBox="true"></e-grid-column>
                <e-grid-column field="SalesOrderName" headerText="SO#" type="string"></e-grid-column>
                <e-grid-column field="ShipmentDate" type="date" headerText="Shipment Date"></e-grid-column>
                <e-grid-column field="WarehouseName"  headerText="Warehouse" type="string"></e-grid-column>
                <e-grid-column field="CompanyId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="SalesOrderId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="ShipmentTypeId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="WarehouseId" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="Remarks" allowSearching="false" allowFiltering="false" visible="false"></e-grid-column>
                <e-grid-column field="ShipmentId" headerText="" allowSearching="false" allowFiltering="false" isPrimaryKey="true" template="#shipmentTemp"></e-grid-column>
            </e-grid-columns>
        </ejs-grid>
    </div>
</section><!-- /.content -->
<script id="shipmentTemp" type="text/x-template">
    <a rel='nofollow' href="/Sales/Shipment/Details?shipmentId=${ShipmentId}"><span class="e-icons e-MT_List"></span></a>
</script>
<script id='dialogtemplate' type="text/x-template">
    <div id="dialogTemp"></div>
</script>
<script src="~/js/grid.js"></script>
<script>
        function load(args) {
            this.columns[3].format = { type: 'date', format: 'dd/MM/yyyy' };
        }
        function actionFailure(args) {
          displayErrors(args)
        }
    function actionComplete(args) {
        if (args.requestType === 'beginEdit' || args.requestType === 'add') {
                let spinner = ej.popups.createSpinner({ target: args.dialog.element });
                ej.popups.showSpinner(args.dialog.element);
                if (args.requestType === 'beginEdit' || args.requestType === 'add') {
                    var ajax = new ej.base.Ajax({
                        url: "@Url.Action($"EditAddPartial", "Shipment")", //render the partial view
                        type: "POST",
                        contentType: "application/json",
                        data: JSON.stringify({ value: args.rowData })
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); 
                        ej.popups.hideSpinner(args.dialog.element);
                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }
            }
        }
</script>
<script type="text/javascript">
    function salesOrderChange(e) {
        $('#SalesOrderName').val(e.itemData.SalesOrderName);
    }
</script>

ByMe.Presentation/Areas/Sales/Views/Shipment/_CreateEditPartial.cshtml
@using BuyMe.Application.Shipment.Commonds
@using Newtonsoft.Json
@model CreateEditShipCommond
@{
    Layout = null;
}
<style>
    .dropDownListTop {
        margin-top: 15px;
    }
</style>
<div>
    <input name="SalesOrderName" id="SalesOrderName" type="hidden"/>
    <input asp-for="ShipmentId" type="hidden" />
    <input asp-for="CompanyId" type="hidden" />
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="ShipmentName" readonly />
                <span class="e-float-line"></span>
                <label asp-for="ShipmentName" class="e-float-text e-label-top">ShipmentName#</label>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <ejs-checkbox id="cbox2" name="IsFullShipment" value="@Model.IsFullShipment" checked="@Model.IsFullShipment" label="IsFullShipment"></ejs-checkbox>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="dropDownListTop">
                <ejs-dropdownlist ejs-for="SalesOrderId" change="salesOrderChange" placeholder="SalesOrder" dataSource="@ViewBag.SalesOrders" popupHeight="200px">
                    <e-dropdownlist-fields text="SalesOrderName" value="SalesOrderId"></e-dropdownlist-fields>
                </ejs-dropdownlist>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="ShipmentDate" type="date" />
                <span class="e-float-line"></span>
                <label asp-for="ShipmentDate" class="e-float-text e-label-top">ShipmentDate</label>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="dropDownListTop">
                <ejs-dropdownlist ejs-for="ShipmentTypeId" dataSource="@ViewBag.ShipmentTypes" placeholder="Shipment Type" popupHeight="200px">
                    <e-dropdownlist-fields text="ShipmentTypeName" value="Id"></e-dropdownlist-fields>
                </ejs-dropdownlist>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="dropDownListTop">
                <ejs-dropdownlist ejs-for="WarehouseId" dataSource="@ViewBag.Warhouses" placeholder="Warhouse" popupHeight="200px">
                    <e-dropdownlist-fields text="WarehouseName" value="WarehouseId"></e-dropdownlist-fields>
                </ejs-dropdownlist>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-8">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="Remarks" />
                <span class="e-float-line"></span>
                <label asp-for="Remarks" class="e-float-text e-label-top">Remarks</label>
            </div>
        </div>
    </div>
</div>

<ejs-scripts></ejs-scripts>