ByMe.Presentation/Areas/Sales/Controllers/InvoiceTypeController.cs
using BuyMe.Application.Common.Exceptions;
using BuyMe.Application.Common.Models;
using BuyMe.Application.Customer.Commonds.CreatEditCustomer;
using BuyMe.Application.Customer.Commonds.DeleteCustomer;
using BuyMe.Application.Customer.Queries.GetCustomers;
using BuyMe.Application.CustomerType.Queries;
using BuyMe.Application.InvoiceType.Commonds.CreatEditIInvoiceType;
using BuyMe.Application.InvoiceType.Commonds.DeletInvoiceType;
using BuyMe.Application.InvoiceType.Queries;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.EJ2.Base;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ByMe.Presentation.Areas.Sales.Controllers
{
    [Authorize(Roles = ApplicationRoles.InvoiceType)]
    public class InvoiceTypeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UrlDatasource([FromBody] DataManagerRequest dm)
        {
            var result = await Mediator.Send(new GetAllInvoiceTypeQueries() { DM = new DataManager(dm.Take, dm.Skip, dm.Search?.FirstOrDefault()?.Key) });
            return Json(result);
        }

        public async Task<ActionResult> CreateEdit([FromBody] CRUDModel<CreatEditInvoiceTypeCommond> value)
        {
            _ = value ?? throw new BadRequestException("Invalid Data");
            value.Value.InvoiceTypeId = await Mediator.Send(value.Value);
            return Json(value.Value);
        }

        public async Task<ActionResult> Delete([FromBody] CRUDModel<InvoiceTypeDto> value)
        {
            _ = await Mediator.Send(new DeleteInvoiceTypeCommond() { InvoiceTypeId = Convert.ToInt32(value.Key) });
            return Json(value);
        }

        public  IActionResult EditAddPartial([FromBody] CRUDModel<CreatEditInvoiceTypeCommond> value)
        {
            return PartialView("_CreateEditPartial", value.Value);
        }
    }
}

ByMe.Presentation/Areas/Sales/Views/InvoiceType/Index.cshtml
@using Newtonsoft.Json;
<link rel="stylesheet" href="~/css/grid.css" />
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Invoice Type
        <small>Sales</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Invoice Type</a></li>
        <li class="active">Sales</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="control-section">
        <ejs-grid id="Grid" actionFailure="actionFailure" actionComplete="actionComplete" toolbar="@(new List<string>() { "Add", "Edit", "Delete","Print","Search" })" allowPaging="true">
            <e-data-manager url="/Sales/InvoiceType/UrlDataSource" insertUrl="/Sales/InvoiceType/CreateEdit" updateUrl="/Sales/InvoiceType/CreateEdit" removeUrl="/Sales/InvoiceType/Delete" adaptor="UrlAdaptor"></e-data-manager>
            <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true" mode="Dialog" template='#dialogtemplate'></e-grid-editSettings>
            <e-grid-columns>
                <e-grid-column field="InvoiceTypeId" headerText="InvoiceTypeId" allowSearching="false" allowFiltering="false" isPrimaryKey="true" visible="false"></e-grid-column>
                <e-grid-column field="InvoiceTypeName" headerText="InvoiceType Name" type="string"></e-grid-column>
                <e-grid-column field="Description" allowSearching="false" allowFiltering="false"  headerText="Description" type="string"></e-grid-column>
            </e-grid-columns>
        </ejs-grid>
    </div>
</section><!-- /.content -->
<script id='dialogtemplate' type="text/x-template">
    <div id="dialogTemp"></div>
</script>
<script src="~/js/grid.js"></script>
<script>
    function actionFailure(args) {
        displayErrors(args)
        }
    function actionComplete(args) {
        if (args.requestType === 'beginEdit' || args.requestType === 'add') {
            args.form.ej2_instances[0].addRules('InvoiceTypeName', { required: true });

                let spinner = ej.popups.createSpinner({ target: args.dialog.element });
                ej.popups.showSpinner(args.dialog.element);
                if (args.requestType === 'beginEdit' || args.requestType === 'add') {
                    var ajax = new ej.base.Ajax({
                        url: "@Url.Action($"EditAddPartial", "InvoiceType")", //render the partial view
                        type: "POST",
                        contentType: "application/json",
                        data: JSON.stringify({ value: args.rowData })
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); //Render the edit form with selected record
                        args.form.elements.namedItem('InvoiceTypeName').focus();
                        ej.popups.hideSpinner(args.dialog.element);
                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }
            }
        }
</script>

ByMe.Presentation/Areas/Sales/Views/InvoiceType/_CreateEditPartial.cshtml
@using BuyMe.Application.InvoiceType.Commonds.CreatEditIInvoiceType
@model CreatEditInvoiceTypeCommond
@{
    Layout = null;
}
<style>
    .dropDownListTop {
        margin-top: 15px;
    }
</style>
<div>
    <input asp-for="InvoiceTypeId" type="hidden" />
    <div class="form-row">
        <div class="form-group col-md-12">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="InvoiceTypeName" />
                <span class="e-float-line"></span>
                <label asp-for="InvoiceTypeName" class="e-float-text e-label-top">InvoiceType Name</label>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <div class="e-float-input e-control-wrapper">
                <input asp-for="Description" />
                <span class="e-float-line"></span>
                <label asp-for="Description" class="e-float-text e-label-top">InvoiceType Description</label>
            </div>
        </div>
    </div>
</div>

<ejs-scripts></ejs-scripts>